### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [Phambanam/Zadanie3#2]
1. Основное замечание: в Вашей программе смешан код, отвечающий на реализацию, и код, отвечающий за отображение. При написании программ с интерфейсом следует выделять как минимум две части: "логика" (model, реализация) и интерфейс. model - это набор классов, который реализует всю логику игры: хранит состояние доски, проверяет правильность и очерёдность хода, определяет конец игры, ведёт счёт и т.п. Для этого этот набор классов должен иметь некоторое количество get методов для получения состояния игры (положения крестиков и ноликов, счёта, текущего активного игрока) и некоторое количество методов, изменяющих состояние игры (начало игры, попытка сделать ход, сигнал об истечении времени). "Логика" ничего не должна знать об интерфейсе и быть самодостаточной, то есть должно быть можно полностью воспроизвести процесс игры, вызывая методы "логики" (например, в тестах). Интерфейс - это набор классов, который отвечает за отображение состояния игры пользователю (с помощью get методов "логики") и передачу управляющих воздействий от него в "логику" (через методы, изменяющие состояние игры).
1. У Вас некоторые классы, поля и методы нарушают правила именования.
1. Если несколько раз нажать на кнопку Start, то запустится несколько таймеров и время будет уменьшаться в несколько раз быстрее.
1. У Вас можно поставить крестик или нолик на место уже стоящей фигуры.
1. Чем у Вас Каро отличается от Гомоку?

**Comment by Phambanam** [comment]
1 Я исправил, если это неверно, пожалуйста, укажите больше
2 Я исправил это, но не знаю, пропало ли это
3 я исправил
4  не понимаю зачем его заменять
5 на самом деле это то же самое, но на вьетнамском это называется Caro

**Comment by maximpetrov** [comment]
1. У Вас всё ещё большая часть кода, отвечающая за реализацию "логики" находится в классах, отвечающих за интерфейс.
1. Вы исправили не все имена. Напоминаю: имена классов должны быть в формате CamelCase (каждое слово с большой буквы), имена констант большими буквами с подчёркиваниями между словами, а все остальные имена (поля, методы, переменные, аргументы) в формате lowerCamelCase (все слова с большой буквы, кроме первого). Часть имен у Вас соответствует этим правилам, а часть - нет.
1. https://github.com/Phambanam/Zadanie3/blob/e4dd1b49c9295a8382ef9f286f95a88420df531d/src/ControllerCaroBoard.java#L31-L37 Не заметил в прошлый раз, что Вы используете `static` поля для доступа к ним без объекта класса. Это очень плохой стиль, не надо так делать.
1. Забыл сказать в прошлый раз, у Вас нет тестов.

**Comment by Phambanam** [comment]
я исправил б но я не понемаю почему в test я не могу создать новый button

**Comment by maximpetrov** [comment]
1. Повторюсь ещё раз. К model относятся только та часть программы, которая отвечает за логику игры, а часть, отвечающая за отображение должна целиком находиться в GUI. Более конкретное правило: в файлах из пакета Model не должно быть импортов из пакета GUI или из javafx. Все импорты javafx относятся к отображению и должны быть в GUI. GUI должен использовать Model, а не наоборот, так что вместо импортов из GUI в Model должны быть импорты из Model в GUI.
1. Пакеты следует называть с маленькой буквы.
1. Вы всё ещё активно используете `static` поля и методы для доступа к единственному экземпляру.
1. Тестировать GUI достаточно сложно и я от Вас этого не прошу, протестировать нужно только Model, но пока она у Вас не выделена, это делать не получится.

**Comment by Phambanam** [comment]
я исправил

**Comment by maximpetrov** [comment]
1. Если пытаться сделать неправильный ход, то таймер хода сбрасывается.
1. Зачем Вам `EvalBoard`? Насколько я вижу он у Вас не используется.
1. Поля должны быть `private`. Для простых полей (примитивных типов) допустимо быть `public`, но они должны быть `final`.
1. У Вас осталось два `static` поля: `View.primaryStage` и `BorderState.boardArr`. Избавьтесь от них.
1. Использовать `accessibleText` для хранения координат, а потом каждый раз разбирать строку, очень плохо. Лучше определите свой класс, наследник `Button`, и добавьте ему координаты в нормальном виде.
1. Проверка правильности хода должна быть в модели (в `BoardState`).

**Comment by Phambanam** [comment]
я исправил

**Comment by maximpetrov** [comment]
1. Вы не исправили 6 пункт.
1. Зачем Вы добавили поле `boardState`, в `Controller`? У Вас `boardState` уже хранится в `player`, почему не взять его? Тем более, что теперь у Вас два не связанных друг с другом экземпляра `BoardState`.

**Comment by Phambanam** [comment]
1.6 я не понимаю!
2. я понял!

**Comment by maximpetrov** [comment]
1. Я хочу, чтобы метод `setPosition` сам проверял, можно ли поставить отметку и возвращал `boolean`: `true` если отметка поставлена и`false`, если она не поставлена.
1. Кстати, вместо `getBoard()` лучше сделать метод `getPosition`, чтобы возвращать массив, а только значение нужной клетки.

**Comment by Phambanam** [comment]
1. Почему надо возвращать boolean ,я только хочу возвращать в клетке , который  игрок 1 или игрок2 играл!

**Comment by maximpetrov** [comment]
Вы можете возвращать что угодно, но по результату должно быть понятно, если отметку поставить нельзя.

**Comment by Phambanam** [comment]
я исправил

**Comment by maximpetrov** [comment]
Вы всё-таки не поняли. Проверка, которую Вы добавили, не имеет смысла. Я хочу, чтобы `setPosition` проверял пуста ли клетка, в которую нужно поставить отметку, и ставил отметку только в пустую клетку.

**Comment by Phambanam** [comment]
да , я понял и исправил

**Comment by maximpetrov** [comment]
Всё ещё не вижу проверку, сейчас Вы всё время возвращаете `true`

**Comment by Phambanam** [comment]
я уже проверил

**Comment by maximpetrov** [comment]
Вы опять сделали почти бесполезную проверку. Вы должны проверить `boardArr[x][y]`, а не `player`.

**Comment by Phambanam** [comment]
я исправил

**Comment by maximpetrov** [comment]
Принято. Пишите отчёт.
